import { ROUTES } from "./routes.config";
import { ROLES } from "./roles.config";

export const roleRoutes = {
  [ROLES.SUPERADMIN]: [
    ROUTES.SUPERADMIN.TIMESHEETAPPROVAL,
   
    ROUTES.SUPERADMIN.REQUESTTIMEOFF,
    
    ROUTES.SUPERADMIN.PROFILE,
    ROUTES.SUPERADMIN.MANAGEMYTEAM,
    ROUTES.SUPERADMIN.ORGCHART,
    ROUTES.SUPERADMIN.GROWTHPORTFOLIO,
    ROUTES.SUPERADMIN.MANAGELEAVE,
    ROUTES.SUPERADMIN.PERSONALTIMESHEET,

  ],

  [ROLES.MANAGER]: [
    ROUTES.MANAGER.TIMESHEETAPPROVAL,
    ROUTES.MANAGER.CLOCKMYTIME,
    ROUTES.MANAGER.REQUESTTIMEOFF,
    ROUTES.MANAGER.PROFILE,
    ROUTES.MANAGER.MANAGEMYTEAM,
    ROUTES.MANAGER.ORGCHART,
    ROUTES.MANAGER.GROWTHPORTFOLIO,
    ROUTES.MANAGER.FEEDBACK,
    ROUTES.MANAGER.LEARNING,
    ROUTES.MANAGER.PAYSLIPS,
    ROUTES.MANAGER.TEAMABSENCE,
    ROUTES.MANAGER.MANAGELEAVE,
    ROUTES.MANAGER.TIMESHEET,
  ],

 

  [ROLES.HR]: [
    ROUTES.HR.TIMESHEETAPPROVAL,
    ROUTES.HR.CLOCKMYTIME,
    ROUTES.HR.REQUESTTIMEOFF,
    ROUTES.HR.PROFILE,
    ROUTES.HR.ORGCHART,
    ROUTES.HR.GROWTHPORTFOLIO,
    ROUTES.HR.FEEDBACK,
    ROUTES.HR.LEARNING,
    ROUTES.HR.PAYSLIPS,
    ROUTES.HR.TEAMABSENCE,
    ROUTES.HR.MANAGEMYTEAM,
    ROUTES.HR.MANAGELEAVE,
    ROUTES.HR.TIMESHEET
  ],

  [ROLES.EMPLOYEE]: [
    ROUTES.EMPLOYEE.CLOCKMYTIME,
    ROUTES.EMPLOYEE.REQUESTTIMEOFF,
    ROUTES.EMPLOYEE.PROFILE,
    ROUTES.EMPLOYEE.ORGCHART,
    ROUTES.EMPLOYEE.GROWTHPORTFOLIO,
    ROUTES.EMPLOYEE.FEEDBACK,
    ROUTES.EMPLOYEE.LEARNING,
    ROUTES.EMPLOYEE.PAYSLIPS,
    ROUTES.EMPLOYEE.TIMESHEET
  ]
  
};
