import { ROUTES } from "./routes.config";
import { ROLES } from "./roles.config";

export const roleRoutes = {
  [ROLES.SUPERADMIN]: [
    ROUTES.SUPERADMIN.TIMESHEETAPPROVAL,
   
    ROUTES.SUPERADMIN.REQUESTTIMEOFF,
    
    ROUTES.SUPERADMIN.PROFILE,
    ROUTES.SUPERADMIN.MANAGEMYTEAM,
    ROUTES.SUPERADMIN.ORGCHART,
    ROUTES.SUPERADMIN.GROWTHPORTFOLIO,
    ROUTES.SUPERADMIN.MANAGELEAVE,
    ROUTES.SUPERADMIN.PERSONALTIMESHEET,
    ROUTES.SUPERADMIN.DASHBOARD,
    // ROUTES.SUPERADMIN.WORKFORCEWITHHR,
    ROUTES.SUPERADMIN.ADMINCREATION,
    ROUTES.SUPERADMIN.ADMINMANAGEMENT,
    ROUTES.SUPERADMIN.ORG,
     ROUTES.SUPERADMIN.POLICIES,
     ROUTES.SUPERADMIN.PAYROLL,
     ROUTES.SUPERADMIN.APPROVALFLOW,
     ROUTES.SUPERADMIN.FEEDBACK
  ],

  [ROLES.MANAGER]: [
    ROUTES.MANAGER.CLOCKMYTIME,
    ROUTES.MANAGER.REQUESTTIMEOFF,
    ROUTES.MANAGER.PROFILE,
    ROUTES.MANAGER.ORGCHART,
    ROUTES.MANAGER.FEEDBACK,
    ROUTES.MANAGER.PAYSLIPS,
    ROUTES.MANAGER.MANAGELEAVE,
    ROUTES.MANAGER.TIMESHEET,
    ROUTES.MANAGER.DASHBOARD,
    ROUTES.MANAGER.NOTIFICATION,
    ROUTES.MANAGER.TIMESHEETREVIEW,
    ROUTES.MANAGER.TASKANDPROJECT,
    ROUTES.MANAGER.PERFORMANCEMANAGEMENT,
    ROUTES.MANAGER.POLICIES,
    ROUTES.MANAGER.INSURANCE,
    ROUTES.MANAGER.LEAVEAPPROVAL,
    ROUTES.MANAGER.TASKASSIGNMENT,
  ],

 

  [ROLES.HR]: [
    ROUTES.HR.DASHBOARD,
    ROUTES.HR.CLOCKMYTIME,
    ROUTES.HR.INSURANCE,
    ROUTES.HR.NOTIFICATION,
    ROUTES.HR.ONBOARDING,
    ROUTES.HR.PAYSLIPS,
    ROUTES.HR.POLICYANDINSURANCECREATION,
    ROUTES.HR.POLICYDOCUMENTS,
    ROUTES.HR.REQUESTTIMEOFF,
    ROUTES.HR.SALARYCREATION,
    ROUTES.HR.TIMESHEET,
    ROUTES.HR.ORGCHART,
    ROUTES.HR,OFFBOARDING,
  ],

  [ROLES.EMPLOYEE]: [
    ROUTES.EMPLOYEE.CLOCKMYTIME,
    ROUTES.EMPLOYEE.REQUESTTIMEOFF,
    ROUTES.EMPLOYEE.VIEWMYPROFILE,
    ROUTES.EMPLOYEE.ORGCHART,
    ROUTES.EMPLOYEE.GROWTHPORTFOLIO,
    ROUTES.EMPLOYEE.INSURANCE,
    ROUTES.EMPLOYEE.LEARNING,
    ROUTES.EMPLOYEE.PAYSLIPS,
    ROUTES.EMPLOYEE.TIMESHEET,
    ROUTES.EMPLOYEE.DASHBOARD,
    ROUTES.EMPLOYEE.NOTIFICATION,
    ROUTES.EMPLOYEE.POLICYDOCUMENTS,

  ]
  
};
